demo=read.csv("CPSData.csv")
met=read.csv("MetroAreaCodes.csv")
cty=read.csv("CountryCodes.csv")
Citizen=sum(demo$Citizenship=="Citizen, Native"| demo$Citizenship=="Citizen, Naturalized")
table(demo$Hispanic,demo$Race)
any(is.na(demo$MetroArea))
#CheCk if pattern eist in missing values
table(demo$Industry,is.na(demo$Married))
table(demo$State,is.na(demo$MetroAreaCode))
table(demo$Region,is.na(demo$MetroAreaCode))
sort(tapply(is.na(demo$MetroAreaCode),demo$State,mean))
demo = merge(demo,met, by.x="MetroAreaCode", by.y="Code", all.x=TRUE)
table(is.na(demo$MetroArea))
sort(table(demo$MetroArea))
sort(tapply(demo$Hispanic,demo$MetroArea,mean))
sort(tapply(demo$Race=="Asian",demo$MetroArea,mean))
sort(tapply(demo$Education == "No high school diploma", demo$MetroArea, mean,na.rm=TRUE))
demo=merge(demo,cty,by.x ="CountryOfBirthCode",by.y ="Code",all.x = TRUE)
table(is.na(demo$Country))
sort(table(demo$Country))
sort(tapply(demo$MetroArea=="New York-Northern New Jersey-Long Island, NY-NJ-PA",demo$Country,mean,na.rm=TRUE))

sort(tapply(demo$Education == "No high school diploma", demo$MetroArea, mean,na.rm=TRUE))
table(demo$Country,demo$MetroArea=="New York-Northern New Jersey-Long Island, NY-NJ-PA",na.rm=TRUE)
table(demo$MetroArea=="New York-Northern New Jersey-Long Island, NY-NJ-PA")
table(demo$MetroArea=="New York-Northern New Jersey-Long Island, NY-NJ-PA",demo$Country=="United States")
(table(demo$MetroArea,demo$Country=="Somalia"))
ind=subset(demo,demo$Country=="Brazil")
max(table(ind$MetroArea)