boeing=read.csv("BoeingStock.csv")
ccs=read.csv("CocaColaStock.csv")
pg=read.csv("ProcterGambleStock.csv")
ibm=read.csv("IBMStock.csv")
ge=read.csv("GEStock.csv")

ibm$Date = as.Date(ibm$Date, "%m/%d/%y")
ge$Date = as.Date(ge$Date, "%m/%d/%y")
pg$Date = as.Date(pg$Date, "%m/%d/%y")
boeing$Date = as.Date(boeing$Date, "%m/%d/%y")
ccs$Date=as.Date(ccs$Date,"%m/%d/%y")
max(im$Date)
plot(ccs$Date,ccs$StockPrice,type = "l",col="red")
lines(pg$Date, pg$StockPrice,col="blue")
abline(v=as.Date(c("2000-03-01")), lwd=2)
abline(v=as.Date(c("1983-01-01")), lwd=0.5)
plot(ccs$Date[301:432], ccs$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
lines(pg$Date[301:432],pg$StockPrice[301:432],type="l",col="blue")
lines(boeing$Date[301:432],boeing$StockPrice[301:432],type = "l",col="coral3")
lines(ibm$Date[301:432],ibm$StockPrice[301:432],type = "l",col="aquamarine")
lines(ge$Date[301:432],ge$StockPrice[301:432],type = "l",col="antiquewhite3")
legend("topright",legend = c("IBM","GE","P&G","Boeing","coca cola"),col = c("aquamarine","antiquewhite3","blue","coral3","red"),lty=c(1,1) ,cex=.75)
abline(v=as.Date(c("2000-03-01")), lwd=2)
abline(v=as.Date(c("1997-10-01","1997-09-01","1997-11-01")), lwd=0.7)

tapply(ibm$StockPrice,months(ibm$Date), mean)
tapply(p&g$StockPrice,months(p&g$Date), mean)
tapply(ge$StockPrice,months(ge$Date), mean)
tapply(ccs$StockPrice,months(ccs$Date), mean)
tapply(boeing$StockPrice,months(boeing$Date), mean)
